version: '3.4'

services:
  ci-build:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./RealTimeApp.sln && dotnet publish ./RealTimeApp.sln -c Release -o ./obj/Docker/publish"
